# Generated by Django 3.0.5 on 2020-05-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('forum_title', models.CharField(max_length=50)),
                ('forum_text', models.TextField(default='none')),
                ('blog_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('forum_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_title', models.CharField(max_length=50)),
                ('comment_text', models.TextField(default='none')),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Forum')),
            ],
        ),
    ]
