# Generated by Django 3.0.5 on 2020-05-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='blog_date',
            new_name='forum_date',
        ),
    ]
