# Generated by Django 3.0.5 on 2020-04-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_type', models.CharField(choices=[('Y', 'SHOW'), ('N', 'NO SHOW')], max_length=1)),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_desc', models.CharField(max_length=1000)),
                ('blog_desc1', models.CharField(max_length=1000)),
                ('blog_desc2', models.CharField(max_length=1000)),
                ('blog_date', models.DateField(auto_now_add=True)),
                ('blog_order', models.IntegerField(default=1, max_length=3)),
            ],
        ),
    ]
