# Generated by Django 3.0.5 on 2020-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200415_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_pic',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
